# Site settings
title: Corsica

clients:

  - name: Visit Corsica
    link: "https://www.visit-corsica.com/en"
    svg: true

  - name: Air Corsica
    link: "https://www.aircorsica.com/flights/"
    svg: true

  - name: France
    link: "https://uk.france.fr/en/corsica"
    svg: true

description: Lose yourself in this Mediterranean hideaway, where the sun blesses a vivid landscape of irresistible beaches, wild forests and jutting peaks.

baseurl: "/corsica" # the subpath of your site, e.g. /blog/
url: "http://mp.secretescapes.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [js/scripts.min.js]
sass:
    sass_dir: css
    style: compressed